# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quarentime-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for quarentime-ios
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # google login
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'


  target 'quarentime-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'quarentime-iosUITests' do
    # Pods for testing
  end

end
